// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package teststructs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTestClient creates a new instance of MockTestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestClient {
	mock := &MockTestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestClient is an autogenerated mock type for the TestClient type
type MockTestClient struct {
	mock.Mock
}

type MockTestClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestClient) EXPECT() *MockTestClient_Expecter {
	return &MockTestClient_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function for the type MockTestClient
func (_mock *MockTestClient) Convert(r *TestResponse) ([]string, *TestCreate, *TestUpdate, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 []string
	var r1 *TestCreate
	var r2 *TestUpdate
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(*TestResponse) ([]string, *TestCreate, *TestUpdate, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*TestResponse) []string); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*TestResponse) *TestCreate); ok {
		r1 = returnFunc(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*TestCreate)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*TestResponse) *TestUpdate); ok {
		r2 = returnFunc(r)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*TestUpdate)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(*TestResponse) error); ok {
		r3 = returnFunc(r)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTestClient_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MockTestClient_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - r *TestResponse
func (_e *MockTestClient_Expecter) Convert(r any) *MockTestClient_Convert_Call {
	return &MockTestClient_Convert_Call{Call: _e.mock.On("Convert", r)}
}

func (_c *MockTestClient_Convert_Call) Run(run func(r *TestResponse)) *MockTestClient_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TestResponse
		if args[0] != nil {
			arg0 = args[0].(*TestResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestClient_Convert_Call) Return(strings []string, testCreate *TestCreate, testUpdate *TestUpdate, err error) *MockTestClient_Convert_Call {
	_c.Call.Return(strings, testCreate, testUpdate, err)
	return _c
}

func (_c *MockTestClient_Convert_Call) RunAndReturn(run func(r *TestResponse) ([]string, *TestCreate, *TestUpdate, error)) *MockTestClient_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTestClient
func (_mock *MockTestClient) Create(rq *TestCreate) (*TestResponse, error) {
	ret := _mock.Called(rq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*TestCreate) (*TestResponse, error)); ok {
		return returnFunc(rq)
	}
	if returnFunc, ok := ret.Get(0).(func(*TestCreate) *TestResponse); ok {
		r0 = returnFunc(rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*TestCreate) error); ok {
		r1 = returnFunc(rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTestClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - rq *TestCreate
func (_e *MockTestClient_Expecter) Create(rq any) *MockTestClient_Create_Call {
	return &MockTestClient_Create_Call{Call: _e.mock.On("Create", rq)}
}

func (_c *MockTestClient_Create_Call) Run(run func(rq *TestCreate)) *MockTestClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TestCreate
		if args[0] != nil {
			arg0 = args[0].(*TestCreate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestClient_Create_Call) Return(testResponse *TestResponse, err error) *MockTestClient_Create_Call {
	_c.Call.Return(testResponse, err)
	return _c
}

func (_c *MockTestClient_Create_Call) RunAndReturn(run func(rq *TestCreate) (*TestResponse, error)) *MockTestClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTestClient
func (_mock *MockTestClient) Delete(id string) (*TestResponse, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*TestResponse, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *TestResponse); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTestClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockTestClient_Expecter) Delete(id any) *MockTestClient_Delete_Call {
	return &MockTestClient_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTestClient_Delete_Call) Run(run func(id string)) *MockTestClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestClient_Delete_Call) Return(testResponse *TestResponse, err error) *MockTestClient_Delete_Call {
	_c.Call.Return(testResponse, err)
	return _c
}

func (_c *MockTestClient_Delete_Call) RunAndReturn(run func(id string) (*TestResponse, error)) *MockTestClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTestClient
func (_mock *MockTestClient) Get(id string) (*TestResponse, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*TestResponse, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *TestResponse); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTestClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockTestClient_Expecter) Get(id any) *MockTestClient_Get_Call {
	return &MockTestClient_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockTestClient_Get_Call) Run(run func(id string)) *MockTestClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestClient_Get_Call) Return(testResponse *TestResponse, err error) *MockTestClient_Get_Call {
	_c.Call.Return(testResponse, err)
	return _c
}

func (_c *MockTestClient_Get_Call) RunAndReturn(run func(id string) (*TestResponse, error)) *MockTestClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTestClient
func (_mock *MockTestClient) List() ([]*TestResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*TestResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*TestResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*TestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTestClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockTestClient_Expecter) List() *MockTestClient_List_Call {
	return &MockTestClient_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockTestClient_List_Call) Run(run func()) *MockTestClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestClient_List_Call) Return(testResponses []*TestResponse, err error) *MockTestClient_List_Call {
	_c.Call.Return(testResponses, err)
	return _c
}

func (_c *MockTestClient_List_Call) RunAndReturn(run func() ([]*TestResponse, error)) *MockTestClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTestClient
func (_mock *MockTestClient) Update(rq *TestUpdate) (*TestResponse, error) {
	ret := _mock.Called(rq)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*TestUpdate) (*TestResponse, error)); ok {
		return returnFunc(rq)
	}
	if returnFunc, ok := ret.Get(0).(func(*TestUpdate) *TestResponse); ok {
		r0 = returnFunc(rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*TestUpdate) error); ok {
		r1 = returnFunc(rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTestClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - rq *TestUpdate
func (_e *MockTestClient_Expecter) Update(rq any) *MockTestClient_Update_Call {
	return &MockTestClient_Update_Call{Call: _e.mock.On("Update", rq)}
}

func (_c *MockTestClient_Update_Call) Run(run func(rq *TestUpdate)) *MockTestClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TestUpdate
		if args[0] != nil {
			arg0 = args[0].(*TestUpdate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestClient_Update_Call) Return(testResponse *TestResponse, err error) *MockTestClient_Update_Call {
	_c.Call.Return(testResponse, err)
	return _c
}

func (_c *MockTestClient_Update_Call) RunAndReturn(run func(rq *TestUpdate) (*TestResponse, error)) *MockTestClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
