// This file is only used for testing purposes.
// Due to the low update frequency, the generation is not automated.
// Simply run the following command from the root of the project:
// protoc -I=. --go_out=./ ./pkg/genericcli/printers/proto_test/test.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/genericcli/printers/proto_test/test.proto

package proto_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_PENDING     State = 1
	State_STATE_ACTIVE      State = 2
	State_STATE_TERMINATED  State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_ACTIVE",
		3: "STATE_TERMINATED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_ACTIVE":      2,
		"STATE_TERMINATED":  3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_genericcli_printers_proto_test_test_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_pkg_genericcli_printers_proto_test_test_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_pkg_genericcli_printers_proto_test_test_proto_rawDescGZIP(), []int{0}
}

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=printers_test.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_pkg_genericcli_printers_proto_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_genericcli_printers_proto_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_pkg_genericcli_printers_proto_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Foo) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

var File_pkg_genericcli_printers_proto_test_test_proto protoreflect.FileDescriptor

const file_pkg_genericcli_printers_proto_test_test_proto_rawDesc = "" +
	"\n" +
	"-pkg/genericcli/printers/proto_test/test.proto\x12\rprinters_test\"E\n" +
	"\x03Foo\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.printers_test.StateR\x05state*Y\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x02\x12\x14\n" +
	"\x10STATE_TERMINATED\x10\x03B$Z\"pkg/genericcli/printers/proto_testb\x06proto3"

var (
	file_pkg_genericcli_printers_proto_test_test_proto_rawDescOnce sync.Once
	file_pkg_genericcli_printers_proto_test_test_proto_rawDescData []byte
)

func file_pkg_genericcli_printers_proto_test_test_proto_rawDescGZIP() []byte {
	file_pkg_genericcli_printers_proto_test_test_proto_rawDescOnce.Do(func() {
		file_pkg_genericcli_printers_proto_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_genericcli_printers_proto_test_test_proto_rawDesc), len(file_pkg_genericcli_printers_proto_test_test_proto_rawDesc)))
	})
	return file_pkg_genericcli_printers_proto_test_test_proto_rawDescData
}

var file_pkg_genericcli_printers_proto_test_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_genericcli_printers_proto_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_genericcli_printers_proto_test_test_proto_goTypes = []any{
	(State)(0),  // 0: printers_test.State
	(*Foo)(nil), // 1: printers_test.Foo
}
var file_pkg_genericcli_printers_proto_test_test_proto_depIdxs = []int32{
	0, // 0: printers_test.Foo.state:type_name -> printers_test.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_genericcli_printers_proto_test_test_proto_init() }
func file_pkg_genericcli_printers_proto_test_test_proto_init() {
	if File_pkg_genericcli_printers_proto_test_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_genericcli_printers_proto_test_test_proto_rawDesc), len(file_pkg_genericcli_printers_proto_test_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_genericcli_printers_proto_test_test_proto_goTypes,
		DependencyIndexes: file_pkg_genericcli_printers_proto_test_test_proto_depIdxs,
		EnumInfos:         file_pkg_genericcli_printers_proto_test_test_proto_enumTypes,
		MessageInfos:      file_pkg_genericcli_printers_proto_test_test_proto_msgTypes,
	}.Build()
	File_pkg_genericcli_printers_proto_test_test_proto = out.File
	file_pkg_genericcli_printers_proto_test_test_proto_goTypes = nil
	file_pkg_genericcli_printers_proto_test_test_proto_depIdxs = nil
}
