name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.x"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -p bugs -p unused --timeout=3m

      - name: Test
        run: |
          make

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.x"

      - name: Run integration tests
        run: make test-integration
