name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1

  test:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    secrets: inherit
    with:
      build: false
      test-command: make test

  integration-tests:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    secrets: inherit
    with:
      build: false
      lint: false
      test-command: make test-integration
